### PR TITLE
migrate to new API 1.7.0

### PR DESCRIPTION
**Pull request by MrMeison**
**Clean up the project:**
* Migrate form typings to @types
* Add powerbi-models for support JSON filter
* Add npm stripts for building and linting
* Update packages to latest version, add missing dependencies ( such as d3, jquery etc.)
* Add tslint with microsoft-contrib rules
* Comment filter logic

### CODE REVIEW

**Comment by MrMeison** [comment]
**Move settings to a separate file**
- Fix lint issues
- Use dataviewutils for parsing settings

**Comment by MrMeison** [comment]
**Optimize header rendering**

- Change PowerMDL font icon to MDL svg icons
- Refactor header and body section

**Comment by MrMeison** [comment]
- Extract data interfaces in separate file
- Add simple filter

**Comment by MrMeison** [comment]
Implement simple filter for values.
_More information_: https://github.com/Microsoft/powerbi-models#getting-started

**Comment by MrMeison** [comment]
- Update vscode settings to 1.7.0 version
- Remove unused external libraries

**Comment by MrMeison** [comment]
**Fix JSONFilter and markup**
- Fix markup - change icon font to svg icon (used MDL icons) 
- Use semantic tags in visuals (e.g. `label`, `header` and `button`)
- Continue extract data interfaces in separate file
- Fix CSS style for new structure
- Remove comment blocks
- Fix JSON filter ( filter only leafs )

**Comment by MrMeison** [comment]
@liprec, please take a look this PR.  You can see the new logic for _JSONFilter(SymanticFilter)_ [here](https://github.com/MrMeison/powerbi-hierarchySlicer/blob/add-json-filter/src/hierarchySlicerWebBehavior.ts#L298-L313)  and [here](https://github.com/MrMeison/powerbi-hierarchySlicer/blob/add-json-filter/src/hierarchySlicerWebBehavior.ts#L330-L355).
You can merge my changes or include only filter logic.
Thank you for this visual!

**Comment by liprec** [comment]
Hi @MrMeison, I will take a look and let you know.
Thanks so far.

**Comment by liprec** [comment]
Hi @MrMeison,

Again thanks for the code review (+rewrite), this helps me a lot.

But there is a problem with the `applyJSON` method: it can only apply to a single column in a table. And that results in a situation show below: the column region is only filtered by the value 'West', but the user expects that the table is should be filtered by 'West' of the 'Alberta' province.
image

Is there a way to solve this kind of filtering?

**Comment by blamrugan** [comment]
Hi @liprec 
is  powerbi-visuals-utils-sqexprutil exists ? if exists where to get this  powerbi-visuals-utils-sqexprutil..

Thanks in Advance
Bala Murugan R

**Comment by liprec** [comment]
@blamrugan this module is not (yet) available as I don't know if this is the way forward regarding slicer selections. But if it will be available it will be an npm package (npmjs.org) and the code will be in a repository in my GitHub account.

**Comment by f14eagle** [comment]
Hi @liprec

I run the code and got issue says powerbi-visuals-utils-sqexprutils/lib/index.d.ts not found. And I've tried a lot to find this module but failed. Looks like it already disappeared on npmjs.org.

Could you advice where can I get this module?

Thanks in advance.

**Comment by liprec** [comment]
Hi @scomb, 
That module is not (yet) published and as long as the visual is not rebuild for the new custom visual API.
-JP

**Comment by MrMeison** [comment]
@liprec PowerBI API version was updated to the required version. Could not you check the PR again? or close it if it is no longer relevant
Thanks!

**Comment by liprec** [comment]
@MrMeison Did you change anything to the code recently? As far as I know the API (v2.1) is still not capable of supporting this kind of scenarios. Looking at the release notes (https://microsoft.github.io/PowerBI-visuals/docs/changelog/api-2-1/) it will be available with v2.2.

**Pull request closed without merging**
